name: Linting

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  yamllint:
    runs-on: ubuntu-22.04
    name: Run yamllint
    steps:
      - name: Check out code
        uses: actions/checkout@v3.2.0

      - name: Get yamllint config file from dotfiles
        env:
          # yamllint disable-line rule:line-length
          CONFIG_FILE: https://raw.githubusercontent.com/bewuethr/dotfiles/master/.config/yamllint/config
        run: curl "$CONFIG_FILE" > .github/workflows/yamllintconfig

      - name: Run YAML linter
        uses: bewuethr/yamllint-action@v1
        with:
          config-file: .github/workflows/yamllintconfig

  markdownlint:
    runs-on: ubuntu-22.04
    name: Run markdownlint
    steps:
      - name: Check out code
        uses: actions/checkout@v3.2.0

      - name: Get mdl style file from dotfiles
        env:
          # yamllint disable-line rule:line-length
          STYLE_FILE: https://raw.githubusercontent.com/bewuethr/dotfiles/master/.config/mdl/style.rb
        run: curl "$STYLE_FILE" > .github/workflows/style.rb

      - name: Run Markdown linter
        uses: bewuethr/mdl-action@v1
        with:
          style-file: .github/workflows/style.rb

  shellcheck:
    runs-on: ubuntu-22.04
    name: Run ShellCheck
    steps:
      - name: Check out code
        uses: actions/checkout@v3.2.0

      - name: Run ShellCheck
        uses: bewuethr/shellcheck-action@v2

  lint:
    name: Run super-linter job
    uses: bewuethr/workflows/.github/workflows/linter.yml@main
    with:
      validate-dockerfile: true
